spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/payment_db
    username: root
    password: 160525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        type:
          preferred_uuid_jdbc_type: CHAR
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:7020}

payment:
  events:
    topic: ${PAYMENT_EVENTS_TOPIC:payment.events}
  vnpay:
    tmn-code: ${VNP_TMN_CODE:QJ6WZ8I1}
    hash-secret: ${VNP_HASH_SECRET:ECDPF2OGRKR3S9IZTWSKG9BG51GED68U}
    url: ${VNP_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: ${VNP_RETURN_URL:https://pet-conflicts-antarctica-all.trycloudflare.com/api/payments/vnpay/return}
    ipn-url: ${VNP_IPN_URL:https://pet-conflicts-antarctica-all.trycloudflare.com/api/payments/vnpay/ipn}
    version: ${VNP_VERSION:2.1.0}
    command: ${VNP_COMMAND:pay}
    curr-code: ${VNP_CURR_CODE:VND}
    locale-default: ${VNP_LOCALE_DEFAULT:vn}
    expire-minutes: ${VNP_EXPIRE_MINUTES:15}
    timezone: ${VNP_TIMEZONE:Asia/Ho_Chi_Minh}
  zalopay:
    app-id: ${ZLP_APP_ID:553}
    key1: ${ZLP_KEY1:9ph31993439}
    key2: ${ZLP_KEY2:Iyz2habByr7S9uE67zH9G8X5rUf2jQu}
    endpoint: ${ZLP_ENDPOINT:https://sb-openapi.zalopay.vn/v2/create}
    callback-url: ${ZLP_CALLBACK_URL:https://your-domain.com/payments/zalopay/callback}
    redirect-url: ${ZLP_REDIRECT_URL:https://your-frontend.com/checkout/result}

order:
  service:
    base-url: ${ORDER_SERVICE_URL:http://localhost:7019}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
logging:
  level:
    org.hibernate.SQL: WARN
