spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://${CATALOG_DB_HOST:mysql}:${CATALOG_DB_PORT:3306}/catalog_db
    username: ${CATALOG_DB_USER:root}
    password: ${CATALOG_DB_PASS:160525}

server:
  port: 7017

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      probes:
        enabled: true
