spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db
    username: root
    password: 160525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/pharmacy}
    keycloak:
      roles-source: realm
      client-id: pharmacy-app
server:
  port: ${SERVER_PORT:7016}
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
