spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: review-service
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/review_db
    username: root
    password: 160525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${SERVER_PORT:7023}
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
cache:
  default-ttl: 600
  invalidation:
    topic: cache-invalidation-events
  ttl:
    product-list: 600
    product-detail: 1800
    category-list: 600
    review: 600
    review-detail: 1800
    inventory-branch: 300
    inventory-product: 300
    inventory-activity: 300
    post-list: 600
    post-detail: 1800
    user-list: 600
    user-detail: 1800
    appointment-user: 600
    appointment-detail: 1800
    appointment-pharmacist: 600
