spring:
  application:
    name: content-service
  datasource:
    url: jdbc:mysql://${CONTENT_DB_HOST:mysql}:${CONTENT_DB_PORT:3306}/content_db
    username: ${CONTENT_DB_USER:root}
    password: ${CONTENT_DB_PASS:160525}

server:
  port: 7031

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      probes:
        enabled: true
