server:
  port: 7024

spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    username: root
    password: 160525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/pharmacy}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/pharmacy/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

appointment:
  autocancel:
    grace-minutes: 10
    interval-ms: 60000
  buffer-minutes: 10
  no-show:
    grace-minutes: 15
    interval-ms: 60000
branch:
  base-url: ${BRANCH_SERVICE_BASE_URL:http://localhost:7030}

services:
  pharmacist:
    url: ${PHARMACIST_SERVICE_URL:http://localhost:7025}
  user:
    url: ${USER_SERVICE_URL:http://localhost:7016}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
