spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6380
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db
    username: root
    password: 160525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/pharmacy}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/pharmacy/protocol/openid-connect/certs}
    keycloak:
      roles-source: realm
      client-id: pharmacy-app
server:
  port: ${SERVER_PORT:7016}
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
cache:
  default-ttl: 600
  invalidation:
    topic: cache-invalidation-events
  ttl:
    product-list: 600
    product-detail: 1800
    category-list: 600
    review: 600
    review-detail: 1800
    inventory-branch: 300
    inventory-product: 300
    inventory-activity: 300
    post-list: 600
    post-detail: 1800
    user-list: 600
    user-detail: 1800
    appointment-user: 600
    appointment-detail: 1800
    appointment-pharmacist: 600
