spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}

server:
  port: 7022

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      probes:
        enabled: true
