spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.backend.common.model.EventEnvelope
  mail:
    host: localhost
    port: 1025
    username: user
    password: pass
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: ${SERVER_PORT:7022}
management:
  endpoints:
    web:
      exposure:
        include: health,info
notification:
  mail:
    to: test@example.com
