spring:
  application:
    name: cart-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/pharmacy}
    keycloak:
      roles-source: realm
      client-id: pharmacy-app
server:
  port: ${SERVER_PORT:7026}
order:
  service:
    base-url: ${ORDER_SERVICE_BASE_URL:http://127.0.0.1:7019}
inventory:
  service:
    base-url: ${INVENTORY_SERVICE_BASE_URL:http://127.0.0.1:7018}
management:
  endpoints:
    web:
      exposure:
        include: health,info
